<?php

namespace AppBundle\Repository;

/**
 * AlertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlertRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEmailByAlert($type, $keyword)
    {
        
        return $this->getEntityManager()
            ->createQuery(
                "SELECT a.email"
                    . " FROM AppBundle:alert a"
                    . " WHERE a.type = '" . $type . "'"
                    . " AND a.keyword = '" .$keyword . "'"
                    . " GROUP BY a.email"
                    . " ORDER BY a.email DESC"
            )
            ->getResult();
    }
}
