<?php

namespace AppBundle\Repository;

/**
 * BlurayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlurayRepository extends \Doctrine\ORM\EntityRepository
{
}
