<?php

namespace AppBundle\Repository;

/**
 * DvdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DvdRepository extends \Doctrine\ORM\EntityRepository
{
}
