<?php

namespace AppBundle\Repository;

/**
 * DvdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DvdRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllBySearch(array $keywords)
    {
        $tpl = "(d.isan LIKE '%{{keyword}}%' OR d.title LIKE '%{{keyword}}%' OR d.director LIKE '%{{keyword}}%')";
        $arrayWhere = [];
        
        foreach ($keywords as $keyword) {
            $arrayWhere[] = str_replace('{{keyword}}', trim($keyword), $tpl);
        }
        
        return $this->getEntityManager()
            ->createQuery(
                'SELECT d'
                    . ' FROM AppBundle:dvd d'
                    . ' WHERE ' . implode(' AND ', $arrayWhere)
                    . ' ORDER BY d.id DESC'
            )
            ->getResult();
    }
}
